import { Ingredient, DailyMealPlan, Member, Product, Recipe, Post, PredefinedIngredient, IngredientCategory, Review, RelatedProduct } from "./types";

export const CATEGORIES: { id: IngredientCategory; label: string; icon: string }[] = [
  { id: 'VEGETABLE', label: '채소', icon: '🥬' },
  { id: 'FRUIT', label: '과일', icon: '🍎' },
  { id: 'MEAT', label: '정육/계란', icon: '🥩' },
  { id: 'SEAFOOD', label: '수산/해물', icon: '🐟' },
  { id: 'GRAIN', label: '곡류/견과', icon: '🍚' },
  { id: 'DAIRY', label: '유제품', icon: '🥛' },
  { id: 'SAUCE', label: '양념/오일', icon: '🧂' },
  { id: 'PROCESSED', label: '가공/냉동', icon: '🥫' },
  { id: 'ETC', label: '기타', icon: '📦' },
];

export const INGREDIENT_UNITS = ['개', 'g', 'kg', 'ml', 'L', '봉', '팩', '단', '모', '캔', '병', '마리', '알'];

export const ALLERGY_TAGS = ['달걀', '우유', '땅콩', '대두', '밀', '고등어', '게', '새우', '돼지고기', '복숭아', '토마토', '아황산류', '호두', '닭고기', '쇠고기', '오징어', '조개류'];
export const DISEASE_TAGS = ['당뇨', '고혈압', '고지혈증', '비만', '신장질환', '위장장애', '통풍'];

// 🌟 영상 기반 대용량 식재료 DB 구축 (약 450종 이상)
export const PREDEFINED_INGREDIENTS: PredefinedIngredient[] = [
  // 1. 채소 (VEGETABLE)
  { name: '양파', category: 'VEGETABLE', icon: '🧅', defaultStorage: 'ROOM', defaultExpiryDays: 14 },
  { name: '적양파', category: 'VEGETABLE', icon: '🧅', defaultStorage: 'ROOM', defaultExpiryDays: 14 },
  { name: '대파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '쪽파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '실파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '마늘', category: 'VEGETABLE', icon: '🧄', defaultStorage: 'FRIDGE', defaultExpiryDays: 30 },
  { name: '다진마늘', category: 'VEGETABLE', icon: '🧄', defaultStorage: 'FRIDGE', defaultExpiryDays: 20 },
  { name: '마늘종', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '생강', category: 'VEGETABLE', icon: '🫚', defaultStorage: 'FRIDGE', defaultExpiryDays: 20 },
  { name: '당근', category: 'VEGETABLE', icon: '🥕', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '감자', category: 'VEGETABLE', icon: '🥔', defaultStorage: 'ROOM', defaultExpiryDays: 30 },
  { name: '고구마', category: 'VEGETABLE', icon: '🍠', defaultStorage: 'ROOM', defaultExpiryDays: 30 },
  { name: '오이', category: 'VEGETABLE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '애호박', category: 'VEGETABLE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '단호박', category: 'VEGETABLE', icon: '🎃', defaultStorage: 'ROOM', defaultExpiryDays: 30 },
  { name: '늙은호박', category: 'VEGETABLE', icon: '🎃', defaultStorage: 'ROOM', defaultExpiryDays: 60 },
  { name: '고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '청양고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '홍고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '꽈리고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '오이고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '피망', category: 'VEGETABLE', icon: '🫑', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '파프리카', category: 'VEGETABLE', icon: '🫑', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '시금치', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '상추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '양상추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '양배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '적양배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '알배기배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '봄동', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '얼갈이', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '열무', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '깻잎', category: 'VEGETABLE', icon: '🍃', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '무', category: 'VEGETABLE', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '총각무', category: 'VEGETABLE', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '콩나물', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '숙주', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '새송이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '팽이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '표고버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '느타리버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '양송이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '목이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '브로콜리', category: 'VEGETABLE', icon: '🥦', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '콜리플라워', category: 'VEGETABLE', icon: '🥦', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '가지', category: 'VEGETABLE', icon: '🍆', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '부추', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '미나리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '쑥갓', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '근대', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '아욱', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '청경채', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '비트', category: 'VEGETABLE', icon: '🩸', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '연근', category: 'VEGETABLE', icon: '🥔', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '우엉', category: 'VEGETABLE', icon: '🪵', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '더덕', category: 'VEGETABLE', icon: '🪵', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '도라지', category: 'VEGETABLE', icon: '🪵', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '옥수수', category: 'VEGETABLE', icon: '🌽', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '토마토', category: 'VEGETABLE', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 7 },
  { name: '방울토마토', category: 'VEGETABLE', icon: '🍅', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '아스파라거스', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '케일', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '샐러리', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '바질', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '로즈마리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '애플민트', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '고수', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '루꼴라', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '무순', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '파슬리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '고사리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '취나물', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '참나물', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '곤드레', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '시래기', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FREEZER', defaultExpiryDays: 180 },
  { name: '죽순', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '콜라비', category: 'VEGETABLE', icon: '🟣', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '래디쉬', category: 'VEGETABLE', icon: '🔴', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },

  // 2. 과일 (FRUIT)
  { name: '사과', category: 'FRUIT', icon: '🍎', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '배', category: 'FRUIT', icon: '🍐', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '바나나', category: 'FRUIT', icon: '🍌', defaultStorage: 'ROOM', defaultExpiryDays: 5 },
  { name: '포도', category: 'FRUIT', icon: '🍇', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '청포도', category: 'FRUIT', icon: '🍇', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '샤인머스켓', category: 'FRUIT', icon: '🍇', defaultStorage: 'FRIDGE', defaultExpiryDays: 10 },
  { name: '딸기', category: 'FRUIT', icon: '🍓', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '귤', category: 'FRUIT', icon: '🍊', defaultStorage: 'ROOM', defaultExpiryDays: 14 },
  { name: '오렌지', category: 'FRUIT', icon: '🍊', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '한라봉', category: 'FRUIT', icon: '🍊', defaultStorage: 'ROOM', defaultExpiryDays: 14 },
  { name: '천혜향', category: 'FRUIT', icon: '🍊', defaultStorage: 'ROOM', defaultExpiryDays: 14 },
  { name: '자몽', category: 'FRUIT', icon: '🍊', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '레몬', category: 'FRUIT', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '라임', category: 'FRUIT', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '수박', category: 'FRUIT', icon: '🍉', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '참외', category: 'FRUIT', icon: '🍈', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '멜론', category: 'FRUIT', icon: '🍈', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '복숭아', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '천도복숭아', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '자두', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '살구', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 4 },
  { name: '감', category: 'FRUIT', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 14 },
  { name: '홍시', category: 'FRUIT', icon: '🍅', defaultStorage: 'FREEZER', defaultExpiryDays: 90 },
  { name: '곶감', category: 'FRUIT', icon: '🍅', defaultStorage: 'FREEZER', defaultExpiryDays: 180 },
  { name: '아보카도', category: 'FRUIT', icon: '🥑', defaultStorage: 'ROOM', defaultExpiryDays: 5 },
  { name: '키위', category: 'FRUIT', icon: '🥝', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '골드키위', category: 'FRUIT', icon: '🥝', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '파인애플', category: 'FRUIT', icon: '🍍', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '망고', category: 'FRUIT', icon: '🥭', defaultStorage: 'ROOM', defaultExpiryDays: 5 },
  { name: '애플망고', category: 'FRUIT', icon: '🥭', defaultStorage: 'ROOM', defaultExpiryDays: 5 },
  { name: '체리', category: 'FRUIT', icon: '🍒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '블루베리', category: 'FRUIT', icon: '🫐', defaultStorage: 'FRIDGE', defaultExpiryDays: 7 },
  { name: '냉동블루베리', category: 'FRUIT', icon: '🫐', defaultStorage: 'FREEZER', defaultExpiryDays: 180 },
  { name: '라즈베리', category: 'FRUIT', icon: '🫐', defaultStorage: 'FREEZER', defaultExpiryDays: 180 },
  { name: '크랜베리', category: 'FRUIT', icon: '🍒', defaultStorage: 'FREEZER', defaultExpiryDays: 180 },
  { name: '석류', category: 'FRUIT', icon: '🔴', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '무화과', category: 'FRUIT', icon: '🍐', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '코코넛', category: 'FRUIT', icon: '🥥', defaultStorage: 'ROOM', defaultExpiryDays: 30 },
  { name: '매실', category: 'FRUIT', icon: '🟢', defaultStorage: 'ROOM', defaultExpiryDays: 7 },
  { name: '오미자', category: 'FRUIT', icon: '🔴', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '유자', category: 'FRUIT', icon: '🟡', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },

  // 3. 정육/계란 (MEAT)
  { name: '계란', category: 'MEAT', icon: '🥚', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '메추리알', category: 'MEAT', icon: '🥚', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '소고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '소고기 국거리', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '소고기 등심', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '소고기 안심', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '소고기 양지', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '소고기 채끝', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '차돌박이', category: 'MEAT', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '우삼겹', category: 'MEAT', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '사골', category: 'MEAT', icon: '🦴', defaultStorage: 'FREEZER', defaultExpiryDays: 90 },
  { name: '다진소고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '돼지고기', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '삼겹살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '목살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '돼지갈비', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '앞다리살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '뒷다리살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '대패삼겹살', category: 'MEAT', icon: '🥓', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '등갈비', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 3 },
  { name: '다진돼지고기', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '닭고기', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '닭볶음탕용', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '닭가슴살', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '닭다리', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '닭날개', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '닭안심', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '오리고기', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 5 },
  { name: '훈제오리', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '양고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '베이컨', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '소시지', category: 'MEAT', icon: '🌭', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '비엔나소세지', category: 'MEAT', icon: '🌭', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '햄', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 21 },
  { name: '샌드위치햄', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 14 },
  { name: '살라미', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 60 },
  { name: '페퍼로니', category: 'MEAT', icon: '🍕', defaultStorage: 'FRIDGE', defaultExpiryDays: 60 },
  { name: '막창', category: 'MEAT', icon: '🥓', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '곱창', category: 'MEAT', icon: '🥓', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '대창', category: 'MEAT', icon: '🥓', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '육회', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 1 },

  // 4. 수산/해물 (SEAFOOD)
  { name: '고등어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '갈치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '삼치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '조기', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '굴비', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 90 },
  { name: '가자미', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '임연수', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '동태', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '코다리', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 90 },
  { name: '대구', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60 },
  { name: '우럭', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '광어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '연어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2 },
  { name: '훈제연어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '참치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '오징어', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FREEZER', defaultExpiryDays: 90 },
  { name: '반건조오징어', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FREEZER', defaultExpiryDays: 90 },
  { name: '낙지', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '쭈꾸미', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30 },
  { name: '문어', category:
