import { Ingredient, DailyMealPlan, Member, Product, Recipe, Post, PredefinedIngredient, IngredientCategory, Review, RelatedProduct } from "./types";
 
export const CATEGORIES: { id: IngredientCategory; label: string; icon: string }[] = [
  { id: 'VEGETABLE', label: '채소', icon: '🥬' },
  { id: 'FRUIT', label: '과일', icon: '🍎' },
  { id: 'MEAT', label: '정육/계란', icon: '🥩' },
  { id: 'SEAFOOD', label: '수산/해물', icon: '🐟' },
  { id: 'GRAIN', label: '곡류/견과', icon: '🍚' },
  { id: 'DAIRY', label: '유제품', icon: '🥛' },
  { id: 'SAUCE', label: '양념/오일', icon: '🧂' },
  { id: 'PROCESSED', label: '가공/냉동', icon: '🥫' },
  { id: 'ETC', label: '기타', icon: '📦' },
];

export const INGREDIENT_UNITS = ['개', 'g', 'kg', 'ml', 'L', '봉', '팩', '단', '모', '캔', '병', '마리', '알', '장', 'T', '근', '통', '박스'];

export const ALLERGY_TAGS = ['난류(달걀)', '우유', '메밀', '땅콩', '대두(콩)', '밀', '고등어', '게', '새우', '돼지고기', '복숭아', '토마토', '아황산류', '호두', '닭고기', '쇠고기', '오징어', '조개류(굴,전복,홍합 등)', '잣'];
export const DISEASE_TAGS = ['당뇨', '고혈압', '고지혈증', '비만/과체중', '신장질환', '위장장애', '통풍', '아토피', '유당불내증'];

// 🌟 [영상 기반] 단위 변환 데이터가 적용된 식재료 DB (약 450종)
export const PREDEFINED_INGREDIENTS: PredefinedIngredient[] = [
  // ㄱ
  { name: '가지', category: 'VEGETABLE', icon: '🍆', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', 'g'] },
  { name: '가리비', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '가다랑어포', category: 'PROCESSED', icon: '🐟', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 50, suggestedUnits: ['봉', 'g'] },
  { name: '간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'T', baseGram: 15, suggestedUnits: ['T', 'ml', '병'] },
  { name: '간장게장', category: 'SEAFOOD', icon: '🦀', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '마리', baseGram: 250, suggestedUnits: ['마리', 'kg'] },
  { name: '갈치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 300, suggestedUnits: ['마리', '토막', 'g'] },
  { name: '감', category: 'FRUIT', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '박스'] },
  { name: '감자', category: 'VEGETABLE', icon: '🥔', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', 'g', '박스'] },
  { name: '감자전분', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', 'g'] },
  { name: '강력분', category: 'GRAIN', icon: '🍞', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'kg'] },
  { name: '강황', category: 'SAUCE', icon: '🟡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'T'] },
  { name: '건고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '근', 'g'] },
  { name: '건미역', category: 'SEAFOOD', icon: '🌿', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', 'g'] },
  { name: '건새우', category: 'SEAFOOD', icon: '🦐', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '검은깨', category: 'GRAIN', icon: '⚫', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '통', baseGram: 100, suggestedUnits: ['통', 'g'] },
  { name: '검은콩', category: 'GRAIN', icon: '🫘', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '게', category: 'SEAFOOD', icon: '🦀', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 300, suggestedUnits: ['마리', 'kg'] },
  { name: '게맛살', category: 'PROCESSED', icon: '🦀', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 30, suggestedUnits: ['개', '팩'] },
  { name: '겨자', category: 'SAUCE', icon: '🟡', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '튜브', baseGram: 35, suggestedUnits: ['튜브', 'g'] },
  { name: '견과류', category: 'GRAIN', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 20, suggestedUnits: ['봉', 'g'] },
  { name: '계란', category: 'MEAT', icon: '🥚', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 60, suggestedUnits: ['개', '판', '알'] },
  { name: '고구마', category: 'VEGETABLE', icon: '🍠', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', 'g', '박스'] },
  { name: '고등어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 400, suggestedUnits: ['마리', 'g', '팩'] },
  { name: '고사리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '고수', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 50, suggestedUnits: ['단', 'g'] },
  { name: '고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 15, suggestedUnits: ['개', '봉', 'g'] },
  { name: '고추기름', category: 'SAUCE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 80, suggestedUnits: ['병', 'ml'] },
  { name: '고추장', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 365, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'g', 'T'] },
  { name: '고춧가루', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '근', baseGram: 600, suggestedUnits: ['근', 'g', 'T'] },
  { name: '곤드레', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '곤약', category: 'PROCESSED', icon: '⬜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 250, suggestedUnits: ['봉', 'g'] },
  { name: '골뱅이', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 400, suggestedUnits: ['캔', 'g'] },
  { name: '공심채', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 200, suggestedUnits: ['단', 'g'] },
  { name: '곶감', category: 'FRUIT', icon: '🍅', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '개', baseGram: 40, suggestedUnits: ['개', '팩'] },
  { name: '과메기', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },
  { name: '과자', category: 'ETC', icon: '🍪', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', 'g'] },
  { name: '광어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', 'g', '팩'] },
  { name: '국간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '국수면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '인분', baseGram: 100, suggestedUnits: ['인분', 'g', '봉'] },
  { name: '굴', category: 'SEAFOOD', icon: '🦪', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'kg', 'g'] },
  { name: '굴소스', category: 'SAUCE', icon: '🦪', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 250, suggestedUnits: ['병', 'T', 'g'] },
  { name: '귤', category: 'FRUIT', icon: '🍊', defaultStorage: 'ROOM', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', '박스', 'g'] },
  { name: '그라나파다노치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '블럭'] },
  { name: '김', category: 'SEAFOOD', icon: '⬛', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '장', baseGram: 2, suggestedUnits: ['장', '봉', '톳'] },
  { name: '김치', category: 'PROCESSED', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '포기', 'g'] },
  { name: '깍두기', category: 'PROCESSED', icon: '🟥', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '깻잎', category: 'VEGETABLE', icon: '🍃', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '묶음', baseGram: 20, suggestedUnits: ['묶음', '장', 'g'] },
  { name: '꼬막', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '꽁치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 150, suggestedUnits: ['마리', 'g'] },
  { name: '꽁치통조림', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 400, suggestedUnits: ['캔', 'g'] },
  { name: '꽃게', category: 'SEAFOOD', icon: '🦀', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 250, suggestedUnits: ['마리', 'kg'] },
  { name: '꽈리고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '꿀', category: 'SAUCE', icon: '🍯', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'g'] },
  { name: '꿀떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'ROOM', defaultExpiryDays: 1, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },

  // ㄴ
  { name: '낙지', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 200, suggestedUnits: ['마리', 'kg'] },
  { name: '날치알', category: 'SEAFOOD', icon: '🟠', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 100, suggestedUnits: ['팩', 'g'] },
  { name: '낫또', category: 'PROCESSED', icon: '🫘', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '팩', baseGram: 50, suggestedUnits: ['팩', 'g'] },
  { name: '냉면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '인분', baseGram: 150, suggestedUnits: ['인분', '봉'] },
  { name: '냉이', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '녹말', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', 'g'] },
  { name: '녹차', category: 'ETC', icon: '🍵', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '티백', baseGram: 2, suggestedUnits: ['티백', '박스'] },
  { name: '누룽지', category: 'GRAIN', icon: '🍘', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '누텔라', category: 'SAUCE', icon: '🍫', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 370, suggestedUnits: ['통', 'T'] },
  { name: '느타리버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },

  // ㄷ
  { name: '다시다', category: 'SAUCE', icon: '🧂', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', 'T', 'g'] },
  { name: '다시마', category: 'SEAFOOD', icon: '🌿', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '장', baseGram: 10, suggestedUnits: ['장', '봉', 'g'] },
  { name: '다진마늘', category: 'VEGETABLE', icon: '🧄', defaultStorage: 'FRIDGE', defaultExpiryDays: 20, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'T', '큐브'] },
  { name: '다진소고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'kg'] },
  { name: '다진돼지고기', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'kg'] },
  { name: '단무지', category: 'PROCESSED', icon: '🟡', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '팩', baseGram: 400, suggestedUnits: ['팩', '개', 'g'] },
  { name: '단호박', category: 'VEGETABLE', icon: '🎃', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 800, suggestedUnits: ['개', 'g'] },
  { name: '달래', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '단', baseGram: 100, suggestedUnits: ['단', 'g'] },
  { name: '닭고기', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', '팩'] },
  { name: '닭가슴살', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '쪽', '팩'] },
  { name: '닭다리', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '개', baseGram: 100, suggestedUnits: ['개', '팩', 'g'] },
  { name: '당근', category: 'VEGETABLE', icon: '🥕', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', 'g'] },
  { name: '당면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '대파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '단', baseGram: 500, suggestedUnits: ['단', '대', 'g'] },
  { name: '대패삼겹살', category: 'MEAT', icon: '🥓', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'kg', '봉'] },
  { name: '도미', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', 'g'] },
  { name: '돈가스', category: 'PROCESSED', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '장', baseGram: 150, suggestedUnits: ['장', '봉'] },
  { name: '돈까스소스', category: 'SAUCE', icon: '🍱', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'g'] },
  { name: '동태', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60, defaultUnit: '마리', baseGram: 600, suggestedUnits: ['마리', '토막', 'g'] },
  { name: '돼지고기', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '돼지갈비', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '대', '근'] },
  { name: '된장', category: 'SAUCE', icon: '🥘', defaultStorage: 'FRIDGE', defaultExpiryDays: 365, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'T', 'g'] },
  { name: '두부', category: 'PROCESSED', icon: '🧊', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '모', baseGram: 300, suggestedUnits: ['모', '팩', 'g'] },
  { name: '두유', category: 'DAIRY', icon: '🥛', defaultStorage: 'ROOM', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 190, suggestedUnits: ['팩', 'ml'] },
  { name: '들기름', category: 'SAUCE', icon: '🏺', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '들깨가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g', 'T'] },
  { name: '딸기', category: 'FRUIT', icon: '🍓', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', '알', 'g'] },
  { name: '딸기잼', category: 'SAUCE', icon: '🍓', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 400, suggestedUnits: ['병', 'T', 'g'] },
  { name: '땅콩', category: 'GRAIN', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '땅콩버터', category: 'SAUCE', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'T'] },
  { name: '떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 300, suggestedUnits: ['팩', '봉', 'g'] },
  { name: '떡갈비', category: 'PROCESSED', icon: '🍖', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '개', 'g'] },
  { name: '떡국떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '떡볶이떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '또띠아', category: 'GRAIN', icon: '🌮', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '장', baseGram: 30, suggestedUnits: ['장', '팩'] },

  // ㄹ
  { name: '라면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 120, suggestedUnits: ['봉', '박스'] },
  { name: '라이스페이퍼', category: 'GRAIN', icon: '📄', defaultStorage: 'ROOM', defaultExpiryDays: 730, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', '장'] },
  { name: '라임', category: 'FRUIT', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', 'g'] },
  { name: '레몬', category: 'FRUIT', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 120, suggestedUnits: ['개', 'g'] },
  { name: '레몬즙', category: 'SAUCE', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 200, suggestedUnits: ['병', 'T'] },
  { name: '로즈마리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },

  // ㅁ
  { name: '마늘', category: 'VEGETABLE', icon: '🧄', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '알', baseGram: 5, suggestedUnits: ['알', '통', 'g'] },
  { name: '마늘종', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '단', baseGram: 300, suggestedUnits: ['단', 'g'] },
  { name: '마라소스', category: 'SAUCE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '팩', baseGram: 100, suggestedUnits: ['팩', 'g'] },
  { name: '마요네즈', category: 'SAUCE', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g', 'T'] },
  { name: '만두', category: 'PROCESSED', icon: '🥟', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '개', 'g'] },
  { name: '맛살', category: 'PROCESSED', icon: '🦀', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 30, suggestedUnits: ['개', '팩'] },
  { name: '맛술', category: 'SAUCE', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '망고', category: 'FRUIT', icon: '🥭', defaultStorage: 'ROOM', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '박스'] },
  { name: '매실청', category: 'SAUCE', icon: '🟢', defaultStorage: 'ROOM', defaultExpiryDays: 730, defaultUnit: '병', baseGram: 1000, suggestedUnits: ['병', 'ml', 'T'] },
  { name: '맥주', category: 'ETC', icon: '🍺', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 355, suggestedUnits: ['캔', '병', 'ml'] },
  { name: '머스타드', category: 'SAUCE', icon: '🌭', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 200, suggestedUnits: ['통', 'g'] },
  { name: '메추리알', category: 'MEAT', icon: '🥚', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '알', baseGram: 10, suggestedUnits: ['알', '판'] },
  { name: '멜론', category: 'FRUIT', icon: '🍈', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '통', baseGram: 1500, suggestedUnits: ['통', '조각'] },
  { name: '멸치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '박스', baseGram: 500, suggestedUnits: ['박스', '봉', 'g'] },
  { name: '멸치액젓', category: 'SAUCE', icon: '🐟', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml', 'T'] },
  { name: '명란젓', category: 'SEAFOOD', icon: '🔴', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '팩', baseGram: 150, suggestedUnits: ['팩', 'g'] },
  { name: '모짜렐라치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '목살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '무', category: 'VEGETABLE', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 1200, suggestedUnits: ['개', '토막', 'g'] },
  { name: '무순', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '팩', baseGram: 30, suggestedUnits: ['팩', 'g'] },
  { name: '무화과', category: 'FRUIT', icon: '🍐', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '개', baseGram: 60, suggestedUnits: ['개', '팩'] },
  { name: '문어', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', 'g'] },
  { name: '물', category: 'ETC', icon: '💧', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'L', baseGram: 1000, suggestedUnits: ['L', '병'] },
  { name: '물엿', category: 'SAUCE', icon: '🍯', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 700, suggestedUnits: ['병', 'T', 'g'] },
  { name: '미나리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 200, suggestedUnits: ['단', 'g'] },
  { name: '미역', category: 'SEAFOOD', icon: '🌿', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 50, suggestedUnits: ['봉', 'g'] },
  { name: '미트볼', category: 'PROCESSED', icon: '🧆', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '밀가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'kg', 'g'] },

  // ㅂ
  { name: '바게트', category: 'GRAIN', icon: '🥖', defaultStorage: 'ROOM', defaultExpiryDays: 2, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '조각'] },
  { name: '바나나', category: 'FRUIT', icon: '🍌', defaultStorage: 'ROOM', defaultExpiryDays: 5, defaultUnit: '송이', baseGram: 1000, suggestedUnits: ['송이', '개'] },
  { name: '바지락', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '바질', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },
  { name: '밤', category: 'GRAIN', icon: '🌰', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '망', baseGram: 500, suggestedUnits: ['망', '알', 'g'] },
  { name: '밥', category: 'GRAIN', icon: '🍚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '공기', baseGram: 210, suggestedUnits: ['공기', 'g'] },
  { name: '방울토마토', category: 'VEGETABLE', icon: '🍅', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', '알', 'g'] },
  { name: '배', category: 'FRUIT', icon: '🍐', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 400, suggestedUnits: ['개', '박스'] },
  { name: '배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '포기', baseGram: 2000, suggestedUnits: ['포기', '통'] },
  { name: '백김치', category: 'PROCESSED', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '통'] },
  { name: '버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', '봉', 'g'] },
  { name: '버터', category: 'DAIRY', icon: '🧈', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '개', baseGram: 450, suggestedUnits: ['개', 'g'] },
  { name: '베이글', category: 'GRAIN', icon: '🥯', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 100, suggestedUnits: ['개', '봉'] },
  { name: '베이컨', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '줄', baseGram: 20, suggestedUnits: ['줄', '팩', 'g'] },
  { name: '복숭아', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 250, suggestedUnits: ['개', '박스'] },
  { name: '부추', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 500, suggestedUnits: ['단', 'g'] },
  { name: '부침가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'g'] },
  { name: '북어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '마리', baseGram: 50, suggestedUnits: ['마리', '봉'] },
  { name: '불고기양념', category: 'SAUCE', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'g'] },
  { name: '브로콜리', category: 'VEGETABLE', icon: '🥦', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '송이'] },
  { name: '블루베리', category: 'FRUIT', icon: '🫐', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 100, suggestedUnits: ['팩', 'g'] },
  { name: '비빔면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 130, suggestedUnits: ['봉', '팩'] },
  { name: '빵', category: 'GRAIN', icon: '🍞', defaultStorage: 'ROOM', defaultExpiryDays: 3, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', '봉'] },
  { name: '빵가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },

  // ㅅ
  { name: '사과', category: 'FRUIT', icon: '🍎', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 250, suggestedUnits: ['개', '박스'] },
  { name: '사이다', category: 'ETC', icon: '🥤', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 355, suggestedUnits: ['캔', '병', 'ml'] },
  { name: '살구', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '개', baseGram: 50, suggestedUnits: ['개', '팩'] },
  { name: '삼겹살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '상추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '장', 'g'] },
  { name: '새우', category: 'SEAFOOD', icon: '🦐', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 20, suggestedUnits: ['마리', '팩', 'g'] },
  { name: '새우젓', category: 'SAUCE', icon: '🦐', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'g', 'T'] },
  { name: '생강', category: 'VEGETABLE', icon: '🫚', defaultStorage: 'FRIDGE', defaultExpiryDays: 20, defaultUnit: '쪽', baseGram: 20, suggestedUnits: ['쪽', 'g'] },
  { name: '생수', category: 'ETC', icon: '💧', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'L'] },
  { name: '생크림', category: 'DAIRY', icon: '🧁', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', 'ml'] },
  { name: '설탕', category: 'SAUCE', icon: '🍬', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g', '봉'] },
  { name: '소고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '소금', category: 'SAUCE', icon: '🧂', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '봉'] },
  { name: '소면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g', '인분'] },
  { name: '소세지', category: 'MEAT', icon: '🌭', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', '개', 'g'] },
  { name: '소주', category: 'ETC', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 360, suggestedUnits: ['병', '잔'] },
  { name: '수박', category: 'FRUIT', icon: '🍉', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '통', baseGram: 6000, suggestedUnits: ['통', '조각'] },
  { name: '순두부', category: 'PROCESSED', icon: '🧊', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '봉', baseGram: 350, suggestedUnits: ['봉', 'g'] },
  { name: '숙주', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '스팸', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 200, suggestedUnits: ['캔', '개'] },
  { name: '시금치', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '단', baseGram: 300, suggestedUnits: ['단', 'g'] },
  { name: '시리얼', category: 'GRAIN', icon: '🥣', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '박스', baseGram: 500, suggestedUnits: ['박스', '봉', 'g'] },
  { name: '식빵', category: 'GRAIN', icon: '🍞', defaultStorage: 'ROOM', defaultExpiryDays: 3, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '장'] },
  { name: '식용유', category: 'SAUCE', icon: '🌻', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 900, suggestedUnits: ['병', 'ml'] },
  { name: '식초', category: 'SAUCE', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '쌀', category: 'GRAIN', icon: '🍚', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '포대'] },
  { name: '쌈장', category: 'SAUCE', icon: '🥘', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'T', 'g'] },
  { name: '쑥갓', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },

  // ㅇ
  { name: '아몬드', category: 'GRAIN', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '아보카도', category: 'FRUIT', icon: '🥑', defaultStorage: 'ROOM', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 170, suggestedUnits: ['개', 'g'] },
  { name: '아이스크림', category: 'ETC', icon: '🍦', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 474, suggestedUnits: ['통', '개'] },
  { name: '애호박', category: 'VEGETABLE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 280, suggestedUnits: ['개', 'g'] },
  { name: '양고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '팩'] },
  { name: '양배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '통', baseGram: 2000, suggestedUnits: ['통', '쪽', 'g'] },
  { name: '양상추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '통', baseGram: 400, suggestedUnits: ['통', 'g'] },
  { name: '양송이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },
  { name: '양조간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '양파', category: 'VEGETABLE', icon: '🧅', defaultStorage: 'ROOM', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '망', 'g'] },
  { name: '어묵', category: 'PROCESSED', icon: '🍥', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '장', 'g'] },
  { name: '얼음', category: 'ETC', icon: '🧊', defaultStorage: 'FREEZER', defaultExpiryDays: 1000, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'kg'] },
  { name: '연근', category: 'VEGETABLE', icon: '🥔', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', 'g'] },
  { name: '연두부', category: 'PROCESSED', icon: '🧊', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 250, suggestedUnits: ['팩', '모', 'g'] },
  { name: '연어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '팩'] },
  { name: '연유', category: 'DAIRY', icon: '🍯', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 500, suggestedUnits: ['캔', '튜브', 'g'] },
  { name: '열무', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '단', baseGram: 800, suggestedUnits: ['단', 'g'] },
  { name: '오렌지', category: 'FRUIT', icon: '🍊', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '박스'] },
  { name: '오렌지주스', category: 'ETC', icon: '🧃', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '병', baseGram: 1000, suggestedUnits: ['병', 'L', 'ml'] },
  { name: '오이', category: 'VEGETABLE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', 'g'] },
  { name: '오징어', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 250, suggestedUnits: ['마리', 'g'] },
  { name: '오징어젓갈', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g'] },
  { name: '오트밀', category: 'GRAIN', icon: '🥣', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '옥수수', category: 'VEGETABLE', icon: '🌽', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', 'g'] },
  { name: '올리고당', category: 'SAUCE', icon: '🍯', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 700, suggestedUnits: ['병', 'T', 'g'] },
  { name: '올리브유', category: 'SAUCE', icon: '🫒', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '와사비', category: 'SAUCE', icon: '🟢', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '튜브', baseGram: 40, suggestedUnits: ['튜브', 'g'] },
  { name: '와인', category: 'ETC', icon: '🍷', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 750, suggestedUnits: ['병', '잔'] },
  { name: '요거트', category: 'DAIRY', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 85, suggestedUnits: ['개', '팩', 'g'] },
  { name: '우동면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '개'] },
  { name: '우유', category: 'DAIRY', icon: '🥛', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: 'ml', baseGram: 1, suggestedUnits: ['ml', 'L', '팩'] },
  { name: '유부', category: 'PROCESSED', icon: '🥟', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '육수', category: 'PROCESSED', icon: '🍲', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', 'L'] },

  // ㅈ
  { name: '자두', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', '팩'] },
  { name: '자몽', category: 'FRUIT', icon: '🍊', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '박스'] },
  { name: '잡채', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '접시'] },
  { name: '잣', category: 'GRAIN', icon: '🥜', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 100, suggestedUnits: ['통', 'g'] },
  { name: '장조림', category: 'PROCESSED', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '통', baseGram: 200, suggestedUnits: ['통', 'g'] },
  { name: '잼', category: 'SAUCE', icon: '🍯', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T'] },
  { name: '전복', category: 'SEAFOOD', icon: '🦪', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '마리', baseGram: 80, suggestedUnits: ['마리', 'kg'] },
  { name: '전분', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', 'g'] },
  { name: '젓갈', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g'] },
  { name: '젤리', category: 'ETC', icon: '🍮', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 50, suggestedUnits: ['봉', '개'] },
  { name: '조개', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '봉'] },
  { name: '족발', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', '족'] },
  { name: '주스', category: 'ETC', icon: '🧃', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '병', baseGram: 1000, suggestedUnits: ['병', 'L', 'ml'] },
  { name: '쥐포', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '장'] },
  { name: '진간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '진미채', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '짜장', category: 'SAUCE', icon: '⚫', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', '인분'] },
  { name: '쫄면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '인분'] },
  { name: '쭈꾸미', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 100, suggestedUnits: ['마리', 'kg'] },

  // ㅊ
  { name: '차', category: 'ETC', icon: '🍵', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '티백', baseGram: 2, suggestedUnits: ['티백', '박스'] },
  { name: '참기름', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T'] },
  { name: '참외', category: 'FRUIT', icon: '🍈', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '봉'] },
  { name: '참치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '팩'] },
  { name: '참치캔', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 150, suggestedUnits: ['캔', '개'] },
  { name: '청경채', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },
  { name: '청양고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', '개', 'g'] },
  { name: '청주', category: 'SAUCE', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '체다치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: '장', baseGram: 18, suggestedUnits: ['장', '팩'] },
  { name: '체리', category: 'FRUIT', icon: '🍒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 300, suggestedUnits: ['팩', 'g'] },
  { name: '초고추장', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'T'] },
  { name: '초콜릿', category: 'ETC', icon: '🍫', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '개', baseGram: 50, suggestedUnits: ['개', '봉'] },
  { name: '총각김치', category: 'PROCESSED', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '통'] },
  { name: '춘장', category: 'SAUCE', icon: '⚫', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '장', baseGram: 18, suggestedUnits: ['장', '팩'] },
  { name: '치즈케이크', category: 'ETC', icon: '🍰', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '조각', baseGram: 100, suggestedUnits: ['조각', '판'] },
  { name: '치킨', category: 'PROCESSED', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 800, suggestedUnits: ['마리', '조각'] },
  { name: '치킨스톡', category: 'SAUCE', icon: '🐔', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 250, suggestedUnits: ['병', 'T'] },
  { name: '칠리소스', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T'] },

  // ㅋ
  { name: '카놀라유', category: 'SAUCE', icon: '🌼', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 900, suggestedUnits: ['병', 'ml'] },
  { name: '카레', category: 'PROCESSED', icon: '🍛', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', '인분'] },
  { name: '칼국수면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '인분', baseGram: 150, suggestedUnits: ['인분', '봉'] },
  { name: '커피', category: 'ETC', icon: '☕', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '잔', baseGram: 200, suggestedUnits: ['잔', 'g'] },
  { name: '케일', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '장', baseGram: 10, suggestedUnits: ['장', '봉'] },
  { name: '케찹', category: 'SAUCE', icon: '🍅', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g'] },
  { name: '코다리', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 400, suggestedUnits: ['마리', '코'] },
  { name: '코코넛', category: 'FRUIT', icon: '🥥', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 1000, suggestedUnits: ['개', '통'] },
  { name: '콜라', category: 'ETC', icon: '🥤', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 250, suggestedUnits: ['캔', '병', 'L'] },
  { name: '콩', category: 'GRAIN', icon: '🫘', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g', '봉'] },
  { name: '콩나물', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '크림치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '통', baseGram: 200, suggestedUnits: ['통', 'g'] },
  { name: '키위', category: 'FRUIT', icon: '🥝', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 100, suggestedUnits: ['개', '팩'] },

  // ㅌ
  { name: '타임', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },
  { name: '탄산수', category: 'ETC', icon: '🫧', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', '캔'] },
  { name: '토마토', category: 'VEGETABLE', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '박스'] },
  { name: '토마토소스', category: 'SAUCE', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 400, suggestedUnits: ['병', 'g'] },
  { name: '통조림옥수수', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 340, suggestedUnits: ['캔', 'g'] },
  { name: '통조림참치', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 150, suggestedUnits: ['캔', 'g'] },
  { name: '통조림햄', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 200, suggestedUnits: ['캔', 'g'] },
  { name: '튀김가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'g'] },
  { name: '트러플', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '알', baseGram: 20, suggestedUnits: ['알', 'g'] },

  // ㅍ
  { name: '파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '단', baseGram: 500, suggestedUnits: ['단', '대', 'g'] },
  { name: '파김치', category: 'PROCESSED', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '통'] },
  { name: '파마산치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '통', baseGram: 100, suggestedUnits: ['통', 'g'] },
  { name: '파스타면', category: 'PROCESSED', icon: '🍝', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', '인분'] },
  { name: '파슬리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },
  { name: '파인애플', category: 'FRUIT', icon: '🍍', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '통', baseGram: 1000, suggestedUnits: ['통', '조각'] },
  { name: '파프리카', category: 'VEGETABLE', icon: '🫑', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '봉'] },
  { name: '팥', category: 'GRAIN', icon: '🫘', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '팽이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '페페론치노', category: 'SAUCE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 30, suggestedUnits: ['병', 'g'] },
  { name: '포도', category: 'FRUIT', icon: '🍇', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '송이', baseGram: 300, suggestedUnits: ['송이', '알'] },
  { name: '포도씨유', category: 'SAUCE', icon: '🍇', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '표고버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 20, suggestedUnits: ['개', '봉'] },
  { name: '피망', category: 'VEGETABLE', icon: '🫑', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', '봉'] },
  { name: '피자', category: 'PROCESSED', icon: '🍕', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '판', baseGram: 400, suggestedUnits: ['판', '조각'] },
  { name: '피클', category: 'SAUCE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'g'] },

  // ㅎ
  { name: '핫소스', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 150, suggestedUnits: ['병', 'g'] },
  { name: '핫도그', category: 'PROCESSED', icon: '🌭', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '개'] },
  { name: '해물', category: 'SEAFOOD', icon: '🦐', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 300, suggestedUnits: ['팩', 'g'] },
  { name: '햄', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '통', 'g'] },
  { name: '현미', category: 'GRAIN', icon: '🌾', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '포대'] },
  { name: '호두', category: 'GRAIN', icon: '🥜', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '호박', category: 'VEGETABLE', icon: '🎃', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 800, suggestedUnits: ['개', 'g'] },
  { name: '호빵', category: 'PROCESSED', icon: '🥟', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', '개'] },
  { name: '홍고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 15, suggestedUnits: ['개', '봉'] },
  { name: '홍합', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '봉'] },
  { name: '후추', category: 'SAUCE', icon: '🧂', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '통', baseGram: 50, suggestedUnits: ['통', 'g'] },
  { name: '훈제오리', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '팩', baseGram: 600, suggestedUnits: ['팩', 'g'] },
  { name: '휘핑크림', category: 'DAIRY', icon: '🧁', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', 'ml'] },
  { name: '흑미', category: 'GRAIN', icon: '🌾', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '봉'] },
];

export const DUMMY_RECIPES: Recipe[] = [
  { 
    id: '1', name: '김치찌개', category: 'KOREAN', type: '국/찌개', tags: ['한식', '얼큰'], allergens: ['돼지고기'], 
    ingredients: [
        { name: '김치', normalizedName: '김치', amount: '200g', quantity: 200, unit: 'g' }, 
        { name: '돼지고기', normalizedName: '돼지고기', amount: '100g', quantity: 100, unit: 'g' }, 
        { name: '두부', normalizedName: '두부', amount: '1/2모', quantity: 0.5, unit: '모' }
    ], 
    steps: ['김치와 고기를 볶는다', '물을 넣고 끓인다', '두부와 파를 넣는다'], 
    nutrition: { calories: 450, carbs: 20, protein: 30, fat: 25 }, cookingTime: 30, difficulty: 'LEVEL1', image: '', rating: 4.5, reviews: [], relatedProducts: [] 
  },
  // ... (다른 레시피들도 위와 같이 ingredients 구조를 { name, normalizedName, amount } 형태로 맞춰주시면 가장 좋습니다. 
  // 현재는 호환성을 위해 기존 string 구조도 에러나지 않게 types.ts를 유연하게 짰지만, 
  // 장기적으로는 위와 같이 normalizedName을 넣어야 냉장고 연동이 완벽해집니다.)
];
export const DUMMY_POSTS: Post[] = []; 
export const TODAY_MEAL: any = {};
