import { Ingredient, DailyMealPlan, Member, Product, Recipe, Post, PredefinedIngredient, IngredientCategory, Review, RelatedProduct } from "./types";

export const CATEGORIES: { id: IngredientCategory; label: string; icon: string }[] = [
  { id: 'VEGETABLE', label: '채소', icon: '🥬' },
  { id: 'FRUIT', label: '과일', icon: '🍎' },
  { id: 'MEAT', label: '정육/계란', icon: '🥩' },
  { id: 'SEAFOOD', label: '수산/해물', icon: '🐟' },
  { id: 'GRAIN', label: '곡류/견과', icon: '🍚' },
  { id: 'DAIRY', label: '유제품', icon: '🥛' },
  { id: 'SAUCE', label: '양념/오일', icon: '🧂' },
  { id: 'PROCESSED', label: '가공/냉동', icon: '🥫' },
  { id: 'ETC', label: '기타', icon: '📦' },
];

export const INGREDIENT_UNITS = ['개', 'g', 'kg', 'ml', 'L', '봉', '팩', '단', '모', '캔', '병', '마리', '알', '장', 'T', '근', '통'];

export const ALLERGY_TAGS = ['달걀', '우유', '땅콩', '대두', '밀', '고등어', '게', '새우', '돼지고기', '복숭아', '토마토', '아황산류', '호두', '닭고기', '쇠고기', '오징어', '조개류'];
export const DISEASE_TAGS = ['당뇨', '고혈압', '고지혈증', '비만', '신장질환', '위장장애', '통풍'];

// 🌟 [영상 기반] 단위 변환 데이터가 적용된 식재료 DB (약 450종)
export const PREDEFINED_INGREDIENTS: PredefinedIngredient[] = [
  // ㄱ
  { name: '가지', category: 'VEGETABLE', icon: '🍆', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', 'g'] },
  { name: '가리비', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '가다랑어포', category: 'PROCESSED', icon: '🐟', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 50, suggestedUnits: ['봉', 'g'] },
  { name: '간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'T', baseGram: 15, suggestedUnits: ['T', 'ml', '병'] },
  { name: '간장게장', category: 'SEAFOOD', icon: '🦀', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '마리', baseGram: 250, suggestedUnits: ['마리', 'kg'] },
  { name: '갈치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 300, suggestedUnits: ['마리', '토막', 'g'] },
  { name: '감', category: 'FRUIT', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '박스'] },
  { name: '감자', category: 'VEGETABLE', icon: '🥔', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', 'g', '박스'] },
  { name: '감자전분', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', 'g'] },
  { name: '강력분', category: 'GRAIN', icon: '🍞', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'kg'] },
  { name: '강황', category: 'SAUCE', icon: '🟡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'T'] },
  { name: '건고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '근', 'g'] },
  { name: '건미역', category: 'SEAFOOD', icon: '🌿', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', 'g'] },
  { name: '건새우', category: 'SEAFOOD', icon: '🦐', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '검은깨', category: 'GRAIN', icon: '⚫', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '통', baseGram: 100, suggestedUnits: ['통', 'g'] },
  { name: '검은콩', category: 'GRAIN', icon: '🫘', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '게', category: 'SEAFOOD', icon: '🦀', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 300, suggestedUnits: ['마리', 'kg'] },
  { name: '게맛살', category: 'PROCESSED', icon: '🦀', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 30, suggestedUnits: ['개', '팩'] },
  { name: '겨자', category: 'SAUCE', icon: '🟡', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '튜브', baseGram: 35, suggestedUnits: ['튜브', 'g'] },
  { name: '견과류', category: 'GRAIN', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 20, suggestedUnits: ['봉', 'g'] },
  { name: '계란', category: 'MEAT', icon: '🥚', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 60, suggestedUnits: ['개', '판', '알'] },
  { name: '고구마', category: 'VEGETABLE', icon: '🍠', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', 'g', '박스'] },
  { name: '고등어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 400, suggestedUnits: ['마리', 'g', '팩'] },
  { name: '고사리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '고수', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 50, suggestedUnits: ['단', 'g'] },
  { name: '고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 15, suggestedUnits: ['개', '봉', 'g'] },
  { name: '고추기름', category: 'SAUCE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 80, suggestedUnits: ['병', 'ml'] },
  { name: '고추장', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 365, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'g', 'T'] },
  { name: '고춧가루', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '근', baseGram: 600, suggestedUnits: ['근', 'g', 'T'] },
  { name: '곤드레', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '곤약', category: 'PROCESSED', icon: '⬜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 250, suggestedUnits: ['봉', 'g'] },
  { name: '골뱅이', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 400, suggestedUnits: ['캔', 'g'] },
  { name: '공심채', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 200, suggestedUnits: ['단', 'g'] },
  { name: '곶감', category: 'FRUIT', icon: '🍅', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '개', baseGram: 40, suggestedUnits: ['개', '팩'] },
  { name: '과메기', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },
  { name: '과자', category: 'ETC', icon: '🍪', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', 'g'] },
  { name: '광어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', 'g', '팩'] },
  { name: '국간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '국수면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '인분', baseGram: 100, suggestedUnits: ['인분', 'g', '봉'] },
  { name: '굴', category: 'SEAFOOD', icon: '🦪', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'kg', 'g'] },
  { name: '굴소스', category: 'SAUCE', icon: '🦪', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 250, suggestedUnits: ['병', 'T', 'g'] },
  { name: '귤', category: 'FRUIT', icon: '🍊', defaultStorage: 'ROOM', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', '박스', 'g'] },
  { name: '그라나파다노치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '블럭'] },
  { name: '김', category: 'SEAFOOD', icon: '⬛', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '장', baseGram: 2, suggestedUnits: ['장', '봉', '톳'] },
  { name: '김치', category: 'PROCESSED', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '포기', 'g'] },
  { name: '깍두기', category: 'PROCESSED', icon: '🟥', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '깻잎', category: 'VEGETABLE', icon: '🍃', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '묶음', baseGram: 20, suggestedUnits: ['묶음', '장', 'g'] },
  { name: '꼬막', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g'] },
  { name: '꽁치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 150, suggestedUnits: ['마리', 'g'] },
  { name: '꽁치통조림', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 400, suggestedUnits: ['캔', 'g'] },
  { name: '꽃게', category: 'SEAFOOD', icon: '🦀', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 250, suggestedUnits: ['마리', 'kg'] },
  { name: '꽈리고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '꿀', category: 'SAUCE', icon: '🍯', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'g'] },
  { name: '꿀떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'ROOM', defaultExpiryDays: 1, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },

  // ㄴ
  { name: '낙지', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 200, suggestedUnits: ['마리', 'kg'] },
  { name: '날치알', category: 'SEAFOOD', icon: '🟠', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 100, suggestedUnits: ['팩', 'g'] },
  { name: '낫또', category: 'PROCESSED', icon: '🫘', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '팩', baseGram: 50, suggestedUnits: ['팩', 'g'] },
  { name: '냉면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '인분', baseGram: 150, suggestedUnits: ['인분', '봉'] },
  { name: '냉이', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '녹말', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', 'g'] },
  { name: '녹차', category: 'ETC', icon: '🍵', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '티백', baseGram: 2, suggestedUnits: ['티백', '박스'] },
  { name: '누룽지', category: 'GRAIN', icon: '🍘', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '누텔라', category: 'SAUCE', icon: '🍫', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 370, suggestedUnits: ['통', 'T'] },
  { name: '느타리버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },

  // ㄷ
  { name: '다시다', category: 'SAUCE', icon: '🧂', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', 'T', 'g'] },
  { name: '다시마', category: 'SEAFOOD', icon: '🌿', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '장', baseGram: 10, suggestedUnits: ['장', '봉', 'g'] },
  { name: '다진마늘', category: 'VEGETABLE', icon: '🧄', defaultStorage: 'FRIDGE', defaultExpiryDays: 20, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'T', '큐브'] },
  { name: '다진소고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'kg'] },
  { name: '다진돼지고기', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'kg'] },
  { name: '단무지', category: 'PROCESSED', icon: '🟡', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '팩', baseGram: 400, suggestedUnits: ['팩', '개', 'g'] },
  { name: '단호박', category: 'VEGETABLE', icon: '🎃', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 800, suggestedUnits: ['개', 'g'] },
  { name: '달래', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '단', baseGram: 100, suggestedUnits: ['단', 'g'] },
  { name: '닭고기', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', '팩'] },
  { name: '닭가슴살', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '쪽', '팩'] },
  { name: '닭다리', category: 'MEAT', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '개', baseGram: 100, suggestedUnits: ['개', '팩', 'g'] },
  { name: '당근', category: 'VEGETABLE', icon: '🥕', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', 'g'] },
  { name: '당면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '대파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '단', baseGram: 500, suggestedUnits: ['단', '대', 'g'] },
  { name: '대패삼겹살', category: 'MEAT', icon: '🥓', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', 'kg', '봉'] },
  { name: '도미', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', 'g'] },
  { name: '돈가스', category: 'PROCESSED', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '장', baseGram: 150, suggestedUnits: ['장', '봉'] },
  { name: '돈까스소스', category: 'SAUCE', icon: '🍱', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'g'] },
  { name: '동태', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 60, defaultUnit: '마리', baseGram: 600, suggestedUnits: ['마리', '토막', 'g'] },
  { name: '돼지고기', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '돼지갈비', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '대', '근'] },
  { name: '된장', category: 'SAUCE', icon: '🥘', defaultStorage: 'FRIDGE', defaultExpiryDays: 365, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'T', 'g'] },
  { name: '두부', category: 'PROCESSED', icon: '🧊', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '모', baseGram: 300, suggestedUnits: ['모', '팩', 'g'] },
  { name: '두유', category: 'DAIRY', icon: '🥛', defaultStorage: 'ROOM', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 190, suggestedUnits: ['팩', 'ml'] },
  { name: '들기름', category: 'SAUCE', icon: '🏺', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '들깨가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g', 'T'] },
  { name: '딸기', category: 'FRUIT', icon: '🍓', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', '알', 'g'] },
  { name: '딸기잼', category: 'SAUCE', icon: '🍓', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 400, suggestedUnits: ['병', 'T', 'g'] },
  { name: '땅콩', category: 'GRAIN', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '땅콩버터', category: 'SAUCE', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'T'] },
  { name: '떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 300, suggestedUnits: ['팩', '봉', 'g'] },
  { name: '떡갈비', category: 'PROCESSED', icon: '🍖', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '개', 'g'] },
  { name: '떡국떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '떡볶이떡', category: 'PROCESSED', icon: '🍡', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '또띠아', category: 'GRAIN', icon: '🌮', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '장', baseGram: 30, suggestedUnits: ['장', '팩'] },

  // ㄹ
  { name: '라면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 120, suggestedUnits: ['봉', '박스'] },
  { name: '라이스페이퍼', category: 'GRAIN', icon: '📄', defaultStorage: 'ROOM', defaultExpiryDays: 730, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', '장'] },
  { name: '라임', category: 'FRUIT', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', 'g'] },
  { name: '레몬', category: 'FRUIT', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 120, suggestedUnits: ['개', 'g'] },
  { name: '레몬즙', category: 'SAUCE', icon: '🍋', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 200, suggestedUnits: ['병', 'T'] },
  { name: '로즈마리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },

  // ㅁ
  { name: '마늘', category: 'VEGETABLE', icon: '🧄', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '알', baseGram: 5, suggestedUnits: ['알', '통', 'g'] },
  { name: '마늘종', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '단', baseGram: 300, suggestedUnits: ['단', 'g'] },
  { name: '마라소스', category: 'SAUCE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '팩', baseGram: 100, suggestedUnits: ['팩', 'g'] },
  { name: '마요네즈', category: 'SAUCE', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g', 'T'] },
  { name: '만두', category: 'PROCESSED', icon: '🥟', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '개', 'g'] },
  { name: '맛살', category: 'PROCESSED', icon: '🦀', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 30, suggestedUnits: ['개', '팩'] },
  { name: '맛술', category: 'SAUCE', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '망고', category: 'FRUIT', icon: '🥭', defaultStorage: 'ROOM', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '박스'] },
  { name: '매실청', category: 'SAUCE', icon: '🟢', defaultStorage: 'ROOM', defaultExpiryDays: 730, defaultUnit: '병', baseGram: 1000, suggestedUnits: ['병', 'ml', 'T'] },
  { name: '맥주', category: 'ETC', icon: '🍺', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 355, suggestedUnits: ['캔', '병', 'ml'] },
  { name: '머스타드', category: 'SAUCE', icon: '🌭', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 200, suggestedUnits: ['통', 'g'] },
  { name: '메추리알', category: 'MEAT', icon: '🥚', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '알', baseGram: 10, suggestedUnits: ['알', '판'] },
  { name: '멜론', category: 'FRUIT', icon: '🍈', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '통', baseGram: 1500, suggestedUnits: ['통', '조각'] },
  { name: '멸치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '박스', baseGram: 500, suggestedUnits: ['박스', '봉', 'g'] },
  { name: '멸치액젓', category: 'SAUCE', icon: '🐟', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml', 'T'] },
  { name: '명란젓', category: 'SEAFOOD', icon: '🔴', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '팩', baseGram: 150, suggestedUnits: ['팩', 'g'] },
  { name: '모짜렐라치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '목살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '무', category: 'VEGETABLE', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 1200, suggestedUnits: ['개', '토막', 'g'] },
  { name: '무순', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '팩', baseGram: 30, suggestedUnits: ['팩', 'g'] },
  { name: '무화과', category: 'FRUIT', icon: '🍐', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '개', baseGram: 60, suggestedUnits: ['개', '팩'] },
  { name: '문어', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 1000, suggestedUnits: ['마리', 'g'] },
  { name: '물', category: 'ETC', icon: '💧', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'L', baseGram: 1000, suggestedUnits: ['L', '병'] },
  { name: '물엿', category: 'SAUCE', icon: '🍯', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 700, suggestedUnits: ['병', 'T', 'g'] },
  { name: '미나리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 200, suggestedUnits: ['단', 'g'] },
  { name: '미역', category: 'SEAFOOD', icon: '🌿', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 50, suggestedUnits: ['봉', 'g'] },
  { name: '미트볼', category: 'PROCESSED', icon: '🧆', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '밀가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'kg', 'g'] },

  // ㅂ
  { name: '바게트', category: 'GRAIN', icon: '🥖', defaultStorage: 'ROOM', defaultExpiryDays: 2, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '조각'] },
  { name: '바나나', category: 'FRUIT', icon: '🍌', defaultStorage: 'ROOM', defaultExpiryDays: 5, defaultUnit: '송이', baseGram: 1000, suggestedUnits: ['송이', '개'] },
  { name: '바지락', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '바질', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },
  { name: '밤', category: 'GRAIN', icon: '🌰', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '망', baseGram: 500, suggestedUnits: ['망', '알', 'g'] },
  { name: '밥', category: 'GRAIN', icon: '🍚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '공기', baseGram: 210, suggestedUnits: ['공기', 'g'] },
  { name: '방울토마토', category: 'VEGETABLE', icon: '🍅', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', '알', 'g'] },
  { name: '배', category: 'FRUIT', icon: '🍐', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 400, suggestedUnits: ['개', '박스'] },
  { name: '배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '포기', baseGram: 2000, suggestedUnits: ['포기', '통'] },
  { name: '백김치', category: 'PROCESSED', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '통'] },
  { name: '버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', '봉', 'g'] },
  { name: '버터', category: 'DAIRY', icon: '🧈', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '개', baseGram: 450, suggestedUnits: ['개', 'g'] },
  { name: '베이글', category: 'GRAIN', icon: '🥯', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 100, suggestedUnits: ['개', '봉'] },
  { name: '베이컨', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '줄', baseGram: 20, suggestedUnits: ['줄', '팩', 'g'] },
  { name: '복숭아', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 250, suggestedUnits: ['개', '박스'] },
  { name: '부추', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '단', baseGram: 500, suggestedUnits: ['단', 'g'] },
  { name: '부침가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'g'] },
  { name: '북어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 365, defaultUnit: '마리', baseGram: 50, suggestedUnits: ['마리', '봉'] },
  { name: '불고기양념', category: 'SAUCE', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'g'] },
  { name: '브로콜리', category: 'VEGETABLE', icon: '🥦', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '송이'] },
  { name: '블루베리', category: 'FRUIT', icon: '🫐', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 100, suggestedUnits: ['팩', 'g'] },
  { name: '비빔면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 130, suggestedUnits: ['봉', '팩'] },
  { name: '빵', category: 'GRAIN', icon: '🍞', defaultStorage: 'ROOM', defaultExpiryDays: 3, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', '봉'] },
  { name: '빵가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },

  // ㅅ
  { name: '사과', category: 'FRUIT', icon: '🍎', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 250, suggestedUnits: ['개', '박스'] },
  { name: '사이다', category: 'ETC', icon: '🥤', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 355, suggestedUnits: ['캔', '병', 'ml'] },
  { name: '살구', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '개', baseGram: 50, suggestedUnits: ['개', '팩'] },
  { name: '삼겹살', category: 'MEAT', icon: '🥓', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '상추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '장', 'g'] },
  { name: '새우', category: 'SEAFOOD', icon: '🦐', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 20, suggestedUnits: ['마리', '팩', 'g'] },
  { name: '새우젓', category: 'SAUCE', icon: '🦐', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'g', 'T'] },
  { name: '생강', category: 'VEGETABLE', icon: '🫚', defaultStorage: 'FRIDGE', defaultExpiryDays: 20, defaultUnit: '쪽', baseGram: 20, suggestedUnits: ['쪽', 'g'] },
  { name: '생수', category: 'ETC', icon: '💧', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'L'] },
  { name: '생크림', category: 'DAIRY', icon: '🧁', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', 'ml'] },
  { name: '설탕', category: 'SAUCE', icon: '🍬', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g', '봉'] },
  { name: '소고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '근', 'kg'] },
  { name: '소금', category: 'SAUCE', icon: '🧂', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '봉'] },
  { name: '소면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g', '인분'] },
  { name: '소세지', category: 'MEAT', icon: '🌭', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', '개', 'g'] },
  { name: '소주', category: 'ETC', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 360, suggestedUnits: ['병', '잔'] },
  { name: '수박', category: 'FRUIT', icon: '🍉', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '통', baseGram: 6000, suggestedUnits: ['통', '조각'] },
  { name: '순두부', category: 'PROCESSED', icon: '🧊', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '봉', baseGram: 350, suggestedUnits: ['봉', 'g'] },
  { name: '숙주', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '스팸', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 200, suggestedUnits: ['캔', '개'] },
  { name: '시금치', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '단', baseGram: 300, suggestedUnits: ['단', 'g'] },
  { name: '시리얼', category: 'GRAIN', icon: '🥣', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '박스', baseGram: 500, suggestedUnits: ['박스', '봉', 'g'] },
  { name: '식빵', category: 'GRAIN', icon: '🍞', defaultStorage: 'ROOM', defaultExpiryDays: 3, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '장'] },
  { name: '식용유', category: 'SAUCE', icon: '🌻', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 900, suggestedUnits: ['병', 'ml'] },
  { name: '식초', category: 'SAUCE', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '쌀', category: 'GRAIN', icon: '🍚', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '포대'] },
  { name: '쌈장', category: 'SAUCE', icon: '🥘', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 500, suggestedUnits: ['통', 'T', 'g'] },
  { name: '쑥갓', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 4, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },

  // ㅇ
  { name: '아몬드', category: 'GRAIN', icon: '🥜', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '아보카도', category: 'FRUIT', icon: '🥑', defaultStorage: 'ROOM', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 170, suggestedUnits: ['개', 'g'] },
  { name: '아이스크림', category: 'ETC', icon: '🍦', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 474, suggestedUnits: ['통', '개'] },
  { name: '애호박', category: 'VEGETABLE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 280, suggestedUnits: ['개', 'g'] },
  { name: '양고기', category: 'MEAT', icon: '🥩', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '팩'] },
  { name: '양배추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '통', baseGram: 2000, suggestedUnits: ['통', '쪽', 'g'] },
  { name: '양상추', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '통', baseGram: 400, suggestedUnits: ['통', 'g'] },
  { name: '양송이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },
  { name: '양조간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '양파', category: 'VEGETABLE', icon: '🧅', defaultStorage: 'ROOM', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '망', 'g'] },
  { name: '어묵', category: 'PROCESSED', icon: '🍥', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '장', 'g'] },
  { name: '얼음', category: 'ETC', icon: '🧊', defaultStorage: 'FREEZER', defaultExpiryDays: 1000, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'kg'] },
  { name: '연근', category: 'VEGETABLE', icon: '🥔', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', 'g'] },
  { name: '연두부', category: 'PROCESSED', icon: '🧊', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 250, suggestedUnits: ['팩', '모', 'g'] },
  { name: '연어', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '팩'] },
  { name: '연유', category: 'DAIRY', icon: '🍯', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 500, suggestedUnits: ['캔', '튜브', 'g'] },
  { name: '열무', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '단', baseGram: 800, suggestedUnits: ['단', 'g'] },
  { name: '오렌지', category: 'FRUIT', icon: '🍊', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '박스'] },
  { name: '오렌지주스', category: 'ETC', icon: '🧃', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '병', baseGram: 1000, suggestedUnits: ['병', 'L', 'ml'] },
  { name: '오이', category: 'VEGETABLE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', 'g'] },
  { name: '오징어', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 250, suggestedUnits: ['마리', 'g'] },
  { name: '오징어젓갈', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g'] },
  { name: '오트밀', category: 'GRAIN', icon: '🥣', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '옥수수', category: 'VEGETABLE', icon: '🌽', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', 'g'] },
  { name: '올리고당', category: 'SAUCE', icon: '🍯', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 700, suggestedUnits: ['병', 'T', 'g'] },
  { name: '올리브유', category: 'SAUCE', icon: '🫒', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '와사비', category: 'SAUCE', icon: '🟢', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '튜브', baseGram: 40, suggestedUnits: ['튜브', 'g'] },
  { name: '와인', category: 'ETC', icon: '🍷', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '병', baseGram: 750, suggestedUnits: ['병', '잔'] },
  { name: '요거트', category: 'DAIRY', icon: '🥣', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 85, suggestedUnits: ['개', '팩', 'g'] },
  { name: '우동면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '개'] },
  { name: '우유', category: 'DAIRY', icon: '🥛', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: 'ml', baseGram: 1, suggestedUnits: ['ml', 'L', '팩'] },
  { name: '유부', category: 'PROCESSED', icon: '🥟', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '육수', category: 'PROCESSED', icon: '🍲', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', 'L'] },

  // ㅈ
  { name: '자두', category: 'FRUIT', icon: '🍑', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '개', baseGram: 80, suggestedUnits: ['개', '팩'] },
  { name: '자몽', category: 'FRUIT', icon: '🍊', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '박스'] },
  { name: '잡채', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '접시'] },
  { name: '잣', category: 'GRAIN', icon: '🥜', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 100, suggestedUnits: ['통', 'g'] },
  { name: '장조림', category: 'PROCESSED', icon: '🥩', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '통', baseGram: 200, suggestedUnits: ['통', 'g'] },
  { name: '잼', category: 'SAUCE', icon: '🍯', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T'] },
  { name: '전복', category: 'SEAFOOD', icon: '🦪', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '마리', baseGram: 80, suggestedUnits: ['마리', 'kg'] },
  { name: '전분', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', 'g'] },
  { name: '젓갈', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g'] },
  { name: '젤리', category: 'ETC', icon: '🍮', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 50, suggestedUnits: ['봉', '개'] },
  { name: '조개', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '봉'] },
  { name: '족발', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', '족'] },
  { name: '주스', category: 'ETC', icon: '🧃', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '병', baseGram: 1000, suggestedUnits: ['병', 'L', 'ml'] },
  { name: '쥐포', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '장'] },
  { name: '진간장', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'T', 'ml'] },
  { name: '진미채', category: 'SEAFOOD', icon: '🦑', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '짜장', category: 'SAUCE', icon: '⚫', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', '인분'] },
  { name: '쫄면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', '인분'] },
  { name: '쭈꾸미', category: 'SEAFOOD', icon: '🐙', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: '마리', baseGram: 100, suggestedUnits: ['마리', 'kg'] },

  // ㅊ
  { name: '차', category: 'ETC', icon: '🍵', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '티백', baseGram: 2, suggestedUnits: ['티백', '박스'] },
  { name: '참기름', category: 'SAUCE', icon: '🏺', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T'] },
  { name: '참외', category: 'FRUIT', icon: '🍈', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 300, suggestedUnits: ['개', '봉'] },
  { name: '참치', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 30, defaultUnit: 'g', baseGram: 1, suggestedUnits: ['g', '팩'] },
  { name: '참치캔', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 150, suggestedUnits: ['캔', '개'] },
  { name: '청경채', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 200, suggestedUnits: ['팩', 'g'] },
  { name: '청양고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', '개', 'g'] },
  { name: '청주', category: 'SAUCE', icon: '🍾', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '체다치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: '장', baseGram: 18, suggestedUnits: ['장', '팩'] },
  { name: '체리', category: 'FRUIT', icon: '🍒', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '팩', baseGram: 300, suggestedUnits: ['팩', 'g'] },
  { name: '초고추장', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'T'] },
  { name: '초콜릿', category: 'ETC', icon: '🍫', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '개', baseGram: 50, suggestedUnits: ['개', '봉'] },
  { name: '총각김치', category: 'PROCESSED', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '통'] },
  { name: '춘장', category: 'SAUCE', icon: '⚫', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '장', baseGram: 18, suggestedUnits: ['장', '팩'] },
  { name: '치즈케이크', category: 'ETC', icon: '🍰', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '조각', baseGram: 100, suggestedUnits: ['조각', '판'] },
  { name: '치킨', category: 'PROCESSED', icon: '🍗', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: '마리', baseGram: 800, suggestedUnits: ['마리', '조각'] },
  { name: '치킨스톡', category: 'SAUCE', icon: '🐔', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 250, suggestedUnits: ['병', 'T'] },
  { name: '칠리소스', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'T'] },

  // ㅋ
  { name: '카놀라유', category: 'SAUCE', icon: '🌼', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 900, suggestedUnits: ['병', 'ml'] },
  { name: '카레', category: 'PROCESSED', icon: '🍛', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 100, suggestedUnits: ['봉', '인분'] },
  { name: '칼국수면', category: 'PROCESSED', icon: '🍜', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '인분', baseGram: 150, suggestedUnits: ['인분', '봉'] },
  { name: '커피', category: 'ETC', icon: '☕', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '잔', baseGram: 200, suggestedUnits: ['잔', 'g'] },
  { name: '케일', category: 'VEGETABLE', icon: '🥬', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '장', baseGram: 10, suggestedUnits: ['장', '봉'] },
  { name: '케찹', category: 'SAUCE', icon: '🍅', defaultStorage: 'FRIDGE', defaultExpiryDays: 180, defaultUnit: '통', baseGram: 300, suggestedUnits: ['통', 'g'] },
  { name: '코다리', category: 'SEAFOOD', icon: '🐟', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '마리', baseGram: 400, suggestedUnits: ['마리', '코'] },
  { name: '코코넛', category: 'FRUIT', icon: '🥥', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 1000, suggestedUnits: ['개', '통'] },
  { name: '콜라', category: 'ETC', icon: '🥤', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '캔', baseGram: 250, suggestedUnits: ['캔', '병', 'L'] },
  { name: '콩', category: 'GRAIN', icon: '🫘', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', 'g', '봉'] },
  { name: '콩나물', category: 'VEGETABLE', icon: '🌱', defaultStorage: 'FRIDGE', defaultExpiryDays: 3, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', 'g'] },
  { name: '크림치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '통', baseGram: 200, suggestedUnits: ['통', 'g'] },
  { name: '키위', category: 'FRUIT', icon: '🥝', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '개', baseGram: 100, suggestedUnits: ['개', '팩'] },

  // ㅌ
  { name: '타임', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },
  { name: '탄산수', category: 'ETC', icon: '🫧', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', '캔'] },
  { name: '토마토', category: 'VEGETABLE', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '박스'] },
  { name: '토마토소스', category: 'SAUCE', icon: '🍅', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 400, suggestedUnits: ['병', 'g'] },
  { name: '통조림옥수수', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 340, suggestedUnits: ['캔', 'g'] },
  { name: '통조림참치', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 150, suggestedUnits: ['캔', 'g'] },
  { name: '통조림햄', category: 'PROCESSED', icon: '🥫', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '캔', baseGram: 200, suggestedUnits: ['캔', 'g'] },
  { name: '튀김가루', category: 'GRAIN', icon: '🥡', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 1000, suggestedUnits: ['봉', 'g'] },
  { name: '트러플', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '알', baseGram: 20, suggestedUnits: ['알', 'g'] },

  // ㅍ
  { name: '파', category: 'VEGETABLE', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '단', baseGram: 500, suggestedUnits: ['단', '대', 'g'] },
  { name: '파김치', category: 'PROCESSED', icon: '🎋', defaultStorage: 'FRIDGE', defaultExpiryDays: 60, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '통'] },
  { name: '파마산치즈', category: 'DAIRY', icon: '🧀', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '통', baseGram: 100, suggestedUnits: ['통', 'g'] },
  { name: '파스타면', category: 'PROCESSED', icon: '🍝', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', '인분'] },
  { name: '파슬리', category: 'VEGETABLE', icon: '🌿', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '팩', baseGram: 10, suggestedUnits: ['팩', 'g'] },
  { name: '파인애플', category: 'FRUIT', icon: '🍍', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '통', baseGram: 1000, suggestedUnits: ['통', '조각'] },
  { name: '파프리카', category: 'VEGETABLE', icon: '🫑', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '봉'] },
  { name: '팥', category: 'GRAIN', icon: '🫘', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '봉', baseGram: 500, suggestedUnits: ['봉', 'g'] },
  { name: '팽이버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 5, defaultUnit: '봉', baseGram: 150, suggestedUnits: ['봉', 'g'] },
  { name: '페페론치노', category: 'SAUCE', icon: '🌶️', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 30, suggestedUnits: ['병', 'g'] },
  { name: '포도', category: 'FRUIT', icon: '🍇', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '송이', baseGram: 300, suggestedUnits: ['송이', '알'] },
  { name: '포도씨유', category: 'SAUCE', icon: '🍇', defaultStorage: 'ROOM', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 500, suggestedUnits: ['병', 'ml'] },
  { name: '표고버섯', category: 'VEGETABLE', icon: '🍄', defaultStorage: 'FRIDGE', defaultExpiryDays: 7, defaultUnit: '개', baseGram: 20, suggestedUnits: ['개', '봉'] },
  { name: '피망', category: 'VEGETABLE', icon: '🫑', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 150, suggestedUnits: ['개', '봉'] },
  { name: '피자', category: 'PROCESSED', icon: '🍕', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '판', baseGram: 400, suggestedUnits: ['판', '조각'] },
  { name: '피클', category: 'SAUCE', icon: '🥒', defaultStorage: 'FRIDGE', defaultExpiryDays: 90, defaultUnit: '병', baseGram: 300, suggestedUnits: ['병', 'g'] },

  // ㅎ
  { name: '핫소스', category: 'SAUCE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 365, defaultUnit: '병', baseGram: 150, suggestedUnits: ['병', 'g'] },
  { name: '핫도그', category: 'PROCESSED', icon: '🌭', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 400, suggestedUnits: ['봉', '개'] },
  { name: '해물', category: 'SEAFOOD', icon: '🦐', defaultStorage: 'FREEZER', defaultExpiryDays: 90, defaultUnit: '팩', baseGram: 300, suggestedUnits: ['팩', 'g'] },
  { name: '햄', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 21, defaultUnit: '개', baseGram: 200, suggestedUnits: ['개', '통', 'g'] },
  { name: '현미', category: 'GRAIN', icon: '🌾', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '포대'] },
  { name: '호두', category: 'GRAIN', icon: '🥜', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 200, suggestedUnits: ['봉', 'g'] },
  { name: '호박', category: 'VEGETABLE', icon: '🎃', defaultStorage: 'ROOM', defaultExpiryDays: 30, defaultUnit: '개', baseGram: 800, suggestedUnits: ['개', 'g'] },
  { name: '호빵', category: 'PROCESSED', icon: '🥟', defaultStorage: 'FREEZER', defaultExpiryDays: 180, defaultUnit: '봉', baseGram: 300, suggestedUnits: ['봉', '개'] },
  { name: '홍고추', category: 'VEGETABLE', icon: '🌶️', defaultStorage: 'FRIDGE', defaultExpiryDays: 10, defaultUnit: '개', baseGram: 15, suggestedUnits: ['개', '봉'] },
  { name: '홍합', category: 'SEAFOOD', icon: '🐚', defaultStorage: 'FRIDGE', defaultExpiryDays: 2, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '봉'] },
  { name: '후추', category: 'SAUCE', icon: '🧂', defaultStorage: 'ROOM', defaultExpiryDays: 1000, defaultUnit: '통', baseGram: 50, suggestedUnits: ['통', 'g'] },
  { name: '훈제오리', category: 'MEAT', icon: '🍖', defaultStorage: 'FRIDGE', defaultExpiryDays: 14, defaultUnit: '팩', baseGram: 600, suggestedUnits: ['팩', 'g'] },
  { name: '휘핑크림', category: 'DAIRY', icon: '🧁', defaultStorage: 'FRIDGE', defaultExpiryDays: 30, defaultUnit: '팩', baseGram: 500, suggestedUnits: ['팩', 'ml'] },
  { name: '흑미', category: 'GRAIN', icon: '🌾', defaultStorage: 'ROOM', defaultExpiryDays: 180, defaultUnit: 'kg', baseGram: 1000, suggestedUnits: ['kg', '봉'] },
];

export const INGREDIENT_DB: { [key: string]: Partial<Ingredient> } = {};

export const DUMMY_MEMBERS: Member[] = [
  { 
    id: 'm1', 
    name: '아빠', 
    relationship: 'ME',
    gender: 'M', 
    birthDate: '1980-05-15', 
    height: 178,
    weight: 75,
    bodyType: 'Average',
    hasNoAllergy: false,
    allergies: ['땅콩'], 
    hasNoDisease: false,
    diseases: ['고혈압'],
    proteinFocus: true,
    quickOnly: false,
    targetCalories: 2200, 
    likes: ['돼지고기', '묵은지'], 
    dislikes: ['오이'], 
    avatarColor: 'bg-blue-500' 
  },
  { 
    id: 'm2', 
    name: '엄마', 
    relationship: 'FAMILY',
    gender: 'F', 
    birthDate: '1982-08-20', 
    height: 165,
    weight: 55,
    bodyType: 'Slim',
    hasNoAllergy: true,
    allergies: [],
    hasNoDisease: true,
    diseases: [],
    proteinFocus: false,
    quickOnly: false,
    targetCalories: 1800, 
    likes: ['연어', '샐러드'], 
    dislikes: ['기름진 고기'], 
    avatarColor: 'bg-pink-500' 
  },
  { 
    id: 'm3', 
    name: '준이', 
    relationship: 'FAMILY',
    gender: 'M', 
    birthDate: '2015-03-10', 
    height: 130,
    weight: 30,
    bodyType: 'Average',
    hasNoAllergy: false,
    allergies: ['계란'],
    hasNoDisease: true,
    diseases: [],
    proteinFocus: true,
    quickOnly: true,
    targetCalories: 1600, 
    likes: ['소세지', '치즈'], 
    dislikes: ['당근', '시금치'], 
    avatarColor: 'bg-green-500' 
  }
];

const DUMMY_REVIEWS: Review[] = [
  { id: 'rev1', userId: 'u5', userName: '주부9단', userAvatar: 'https://ui-avatars.com/api/?name=Ju&background=FFD700', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=300', rating: 5, content: '아이들이 너무 좋아해요! 간편하게 만들 수 있어서 자주 해먹습니다.', date: '2024.05.21' },
  { id: 'rev2', userId: 'u6', userName: '자취생', userAvatar: 'https://ui-avatars.com/api/?name=Ja&background=87CEEB', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=300', rating: 4, content: '냉장고 재료 처리하기 딱 좋네요.', date: '2024.05.20' },
  { id: 'rev3', userId: 'u7', userName: '요리초보', userAvatar: 'https://ui-avatars.com/api/?name=Yo&background=FFB6C1', rating: 5, content: '레시피가 상세해서 따라하기 쉬웠어요.', date: '2024.05.19' },
];

const DUMMY_RELATED_PRODUCTS: RelatedProduct[] = [
  { id: 'rp1', name: '유기농 깐양파 500g', price: 3500, image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa829?q=80&w=200', link: '#' },
  { id: 'rp2', name: '무항생제 1등급 계란', price: 8900, image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?q=80&w=200', link: '#' },
  { id: 'rp3', name: '국산 콩나물 300g', price: 1500, image: 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=200', link: '#' },
];

const createRecipe = (
  id: string, name: string, type: any, category: any, 
  cal: number, carb: number, prot: number, fat: number,
  time: number, diff: 'EASY' | 'MEDIUM' | 'HARD',
  ings: string[], steps: string[], img: string,
  extraTags: string[] = [] 
): Recipe => ({
  id, name, image: img, 
  type, category,
  tags: [...ings.slice(0, 3), ...extraTags], 
  allergens: [],
  ingredients: ings.map(n => ({ name: n, amount: '적당량' })),
  steps,
  nutrition: { calories: cal, carbs: carb, protein: prot, fat: fat },
  cookingTime: time,
  difficulty: diff,
  matchRate: 0,
  rating: 4.5 + Math.random() * 0.5,
  reviews: DUMMY_REVIEWS,
  relatedProducts: DUMMY_RELATED_PRODUCTS
});

export const DUMMY_RECIPES: Recipe[] = [
  // Rice
  createRecipe('r1', '현미밥', 'RICE', 'KOREAN', 320, 70, 6, 1, 30, 'EASY', ['현미', '쌀', '물'], ['현미와 쌀을 씻습니다', '물을 맞추어 밥을 짓습니다'], 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?q=80&w=600', ['다이어트']),
  createRecipe('r15', '카레라이스', 'RICE', 'FUSION', 650, 80, 15, 20, 30, 'EASY', ['카레가루', '감자', '양파', '당근', '돼지고기'], ['재료를 볶습니다', '물과 카레를 넣고 끓여 밥 위에 얹습니다'], 'https://images.unsplash.com/photo-1541781777631-fa9531908431?q=80&w=600'),
  createRecipe('r17', '비빔밥', 'RICE', 'KOREAN', 600, 70, 20, 15, 20, 'MEDIUM', ['밥', '나물모듬', '고추장', '계란'], ['밥 위에 나물과 계란을 올립니다', '고추장에 비벼 먹습니다'], 'https://images.unsplash.com/photo-1553163147-621957516d38?q=80&w=600', ['건강']),
  createRecipe('r21', '콩나물밥', 'RICE', 'KOREAN', 400, 70, 10, 5, 30, 'EASY', ['쌀', '콩나물', '간장양념'], ['콩나물을 얹어 밥을 짓습니다', '양념장에 비벼 먹습니다'], 'https://images.unsplash.com/photo-1627209707174-8b0105312351?q=80&w=600', ['다이어트']),
  createRecipe('r30', '짜장밥', 'RICE', 'CHINESE', 600, 85, 20, 25, 25, 'MEDIUM', ['춘장', '양파', '감자', '돼지고기'], ['춘장을 볶습니다', '야채와 고기를 볶아 춘장과 섞습니다', '밥 위에 얹습니다'], 'https://images.unsplash.com/photo-1563897539633-7374c276c212?q=80&w=600'),
  
  // Soup
  createRecipe('r2', '쇠고기 미역국', 'SOUP', 'KOREAN', 180, 5, 15, 10, 40, 'MEDIUM', ['건미역', '소고기', '국간장', '마늘'], ['미역을 불립니다', '고기를 볶다가 물과 미역을 넣고 끓입니다', '간장으로 간을 합니다'], 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=600', ['국물요리']),
  createRecipe('r8', '된장찌개', 'SOUP', 'KOREAN', 150, 10, 12, 5, 25, 'MEDIUM', ['된장', '두부', '애호박', '감자'], ['육수에 된장을 풉니다', '야채와 두부를 넣고 끓입니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['건강']),
  createRecipe('r9', '김치찌개', 'SOUP', 'KOREAN', 350, 15, 20, 25, 30, 'MEDIUM', ['김치', '돼지고기', '두부', '파'], ['김치와 고기를 볶습니다', '물을 붓고 푹 끓입니다', '두부를 넣습니다'], 'https://images.unsplash.com/photo-1552611052-50e7063fcd45?q=80&w=600'),
  createRecipe('r14', '어묵국', 'SOUP', 'KOREAN', 120, 10, 8, 5, 15, 'EASY', ['어묵', '무', '다시마', '파'], ['육수를 냅니다', '어묵을 넣고 끓입니다'], 'https://images.unsplash.com/photo-1627209707174-8b0105312351?q=80&w=600'),
  createRecipe('r18', '순두부찌개', 'SOUP', 'KOREAN', 280, 10, 20, 18, 20, 'MEDIUM', ['순두부', '바지락', '계란', '고추기름'], ['야채를 볶아 고추기름을 냅니다', '물과 순두부를 넣고 끓입니다'], 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600'),
  createRecipe('r22', '소고기 뭇국', 'SOUP', 'KOREAN', 150, 5, 20, 8, 40, 'MEDIUM', ['소고기', '무', '파', '마늘'], ['고기와 무를 볶습니다', '물을 붓고 푹 끓입니다'], 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=600', ['국물요리']),
  createRecipe('r27', '크림 스프', 'SOUP', 'WESTERN', 200, 15, 5, 12, 10, 'EASY', ['크림스프분말', '우유', '크루통'], ['분말을 물과 우유에 풉니다', '끓입니다'], 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=600'),
  createRecipe('r42', '만두국', 'SOUP', 'KOREAN', 400, 50, 15, 10, 20, 'EASY', ['만두', '사골육수', '계란', '파'], ['육수를 끓입니다', '만두를 넣고 익힙니다'], 'https://images.unsplash.com/photo-1542385151-efd90007e2a7?q=80&w=600'),
  createRecipe('r43', '동태찌개', 'SOUP', 'KOREAN', 250, 10, 25, 5, 30, 'HARD', ['동태', '무', '두부', '쑥갓'], ['재료를 손질합니다', '양념을 풀어 끓입니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['국물요리']),
  createRecipe('r44', '꽃게탕', 'SOUP', 'KOREAN', 280, 15, 20, 5, 40, 'HARD', ['꽃게', '된장', '무', '호박'], ['꽃게를 손질합니다', '된장 육수에 끓입니다'], 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?q=80&w=600', ['국물요리']),
  createRecipe('r45', '오징어국', 'SOUP', 'KOREAN', 150, 10, 15, 3, 20, 'MEDIUM', ['오징어', '무', '파', '고춧가루'], ['오징어와 무를 끓입니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['국물요리']),

  // Main Dish
  createRecipe('r3', '제육볶음', 'MAIN', 'KOREAN', 550, 20, 35, 30, 25, 'MEDIUM', ['돼지고기', '고추장', '양파', '대파'], ['고기를 양념에 재웁니다', '센 불에 빠르게 볶아냅니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['야식']),
  createRecipe('r6', '잡채', 'MAIN', 'KOREAN', 400, 60, 8, 12, 50, 'HARD', ['당면', '시금치', '당근', '양파', '버섯', '돼지고기'], ['당면을 삶습니다', '각 재료를 볶습니다', '간장 양념에 버무립니다'], 'https://images.unsplash.com/photo-1626084025846-527e0258163f?q=80&w=600'),
  createRecipe('r7', '오징어 볶음', 'MAIN', 'KOREAN', 380, 15, 30, 10, 20, 'MEDIUM', ['오징어', '양배추', '고춧가루', '설탕'], ['오징어를 손질합니다', '양념장과 야채를 넣고 볶습니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['야식']),
  createRecipe('r12', '돈육 메추리알 장조림', 'MAIN', 'KOREAN', 300, 10, 25, 15, 45, 'MEDIUM', ['돼지고기 안심', '메추리알', '간장', '설탕'], ['고기를 삶습니다', '간장 소스에 고기와 메추리알을 조립니다'], 'https://images.unsplash.com/photo-1626084025846-527e0258163f?q=80&w=600', ['도시락']),
  createRecipe('r13', '떡볶이', 'MAIN', 'KOREAN', 600, 100, 10, 10, 20, 'EASY', ['떡', '어묵', '고추장', '설탕', '파'], ['육수에 고추장을 풉니다', '떡과 어묵을 넣고 졸입니다'], 'https://images.unsplash.com/photo-1580651315530-69c8e0026377?q=80&w=600', ['야식']),
  createRecipe('r19', '갈치구이', 'MAIN', 'KOREAN', 200, 0, 25, 10, 20, 'MEDIUM', ['갈치', '소금', '식용유'], ['갈치에 소금을 뿌립니다', '팬에 굽습니다'], 'https://images.unsplash.com/photo-1534939561126-855f8621818e?q=80&w=600', ['건강']),
  createRecipe('r23', '닭갈비', 'MAIN', 'KOREAN', 500, 30, 35, 20, 30, 'MEDIUM', ['닭고기', '고구마', '양배추', '떡'], ['양념에 재운 닭을 야채와 볶습니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['야식']),
  createRecipe('r26', '토마토 스파게티', 'MAIN', 'WESTERN', 550, 80, 20, 15, 20, 'EASY', ['스파게티면', '토마토소스', '베이컨', '양파'], ['면을 삶습니다', '소스와 함께 볶습니다'], 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=600'),
  createRecipe('r28', '함박스테이크', 'MAIN', 'WESTERN', 600, 20, 40, 35, 40, 'HARD', ['다진소고기', '다진돼지고기', '양파', '빵가루'], ['고기를 반죽해 굽습니다', '소스를 뿌립니다'], 'https://images.unsplash.com/photo-1529042410759-befb1204b468?q=80&w=600', ['도시락']),
  createRecipe('r29', '마파두부', 'MAIN', 'CHINESE', 450, 20, 25, 30, 20, 'MEDIUM', ['두부', '다진돼지고기', '두반장', '파'], ['고기를 볶다가 소스와 물을 넣습니다', '두부를 넣고 졸입니다'], 'https://images.unsplash.com/photo-1536304993881-ff000997fb50?q=80&w=600', ['야식']),
  createRecipe('r41', '수제비', 'MAIN', 'KOREAN', 450, 80, 15, 5, 40, 'MEDIUM', ['밀가루', '감자', '호박', '멸치육수'], ['반죽을 합니다', '육수에 떼어 넣습니다'], 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=600'),
  createRecipe('r46', '보쌈', 'MAIN', 'KOREAN', 600, 5, 40, 45, 60, 'HARD', ['돼지고기 수육용', '마늘', '양파', '된장'], ['고기를 향신채와 삶습니다'], 'https://images.unsplash.com/photo-1544025162-d76690b60f61?q=80&w=600', ['야식']),
  createRecipe('r47', '찜닭', 'MAIN', 'KOREAN', 550, 40, 35, 20, 50, 'HARD', ['닭', '당면', '간장', '고추'], ['닭을 손질합니다', '간장 소스에 조립니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600', ['야식']),
  createRecipe('r48', '삼치구이', 'MAIN', 'KOREAN', 250, 0, 30, 15, 20, 'EASY', ['삼치', '소금'], ['삼치를 굽습니다'], 'https://images.unsplash.com/photo-1534939561126-855f8621818e?q=80&w=600'),
  createRecipe('r49', '조기구이', 'MAIN', 'KOREAN', 150, 0, 20, 8, 20, 'EASY', ['조기', '식용유'], ['조기를 굽습니다'], 'https://images.unsplash.com/photo-1534939561126-855f8621818e?q=80&w=600'),
  createRecipe('r50', '훈제오리 볶음', 'MAIN', 'KOREAN', 400, 5, 20, 35, 10, 'EASY', ['훈제오리', '양파', '부추'], ['오리를 볶다가 야채를 넣습니다'], 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?q=80&w=600'),

  // Side Dish / Noodle
  createRecipe('r4', '계란말이', 'SIDE', 'KOREAN', 250, 2, 12, 18, 15, 'EASY', ['계란', '당근', '파', '소금'], ['계란을 풉니다', '야채를 다져 넣습니다', '팬에 말아가며 익힙니다'], 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=600', ['도시락']),
  createRecipe('r5', '시금치 나물', 'SIDE', 'KOREAN', 60, 5, 3, 2, 15, 'EASY', ['시금치', '참기름', '깨', '소금'], ['시금치를 데칩니다', '찬물에 헹궈 물기를 짭니다', '양념에 무칩니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['다이어트', '건강']),
  createRecipe('r10', '숙주나물', 'SIDE', 'KOREAN', 40, 3, 2, 1, 10, 'EASY', ['숙주', '참기름', '소금'], ['숙주를 데칩니다', '소금과 참기름으로 간합니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['다이어트']),
  createRecipe('r11', '깍두기', 'SIDE', 'KOREAN', 30, 5, 1, 0, 60, 'MEDIUM', ['무', '고춧가루', '새우젓', '파'], ['무를 깍둑 썹니다', '절인 후 양념에 버무립니다'], 'https://images.unsplash.com/photo-1550950158-d0d960dff51b?q=80&w=600'),
  createRecipe('r16', '잔치국수', 'NOODLE', 'KOREAN', 500, 80, 15, 5, 20, 'MEDIUM', ['소면', '멸치육수', '애호박', '김가루'], ['육수를 끓입니다', '면을 삶아 육수를 붓고 고명을 올립니다'], 'https://images.unsplash.com/photo-1626084025846-527e0258163f?q=80&w=600'),
  createRecipe('r20', '브로콜리 숙회', 'SIDE', 'WESTERN', 50, 5, 3, 0, 10, 'EASY', ['브로콜리', '초고추장'], ['브로콜리를 데칩니다', '초장을 곁들입니다'], 'https://images.unsplash.com/photo-1615485499978-0242449a6061?q=80&w=600', ['다이어트', '건강']),
  createRecipe('r24', '감자채 볶음', 'SIDE', 'KOREAN', 120, 20, 2, 5, 15, 'EASY', ['감자', '양파', '당근', '소금'], ['감자를 채 썰어 볶습니다', '소금으로 간합니다'], 'https://images.unsplash.com/photo-1618449845529-688998efd33d?q=80&w=600'),
  createRecipe('r25', '김 구이', 'SIDE', 'KOREAN', 20, 1, 1, 1, 5, 'EASY', ['김', '참기름', '소금'], ['김에 기름을 바르고 굽습니다'], 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=600', ['다이어트']),
  createRecipe('r31', '오이무침', 'SIDE', 'KOREAN', 40, 8, 1, 0, 10, 'EASY', ['오이', '양파', '고춧가루', '식초'], ['오이를 썹니다', '양념에 무칩니다'], 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=600', ['다이어트']),
  createRecipe('r32', '멸치볶음', 'SIDE', 'KOREAN', 150, 10, 15, 8, 15, 'EASY', ['잔멸치', '견과류', '올리고당', '간장'], ['멸치를 볶습니다', '양념에 버무립니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['도시락']),
  createRecipe('r33', '진미채볶음', 'SIDE', 'KOREAN', 200, 25, 15, 5, 15, 'MEDIUM', ['진미채', '고추장', '마요네즈'], ['진미채를 불립니다', '양념장에 볶습니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['도시락']),
  createRecipe('r34', '감자조림', 'SIDE', 'KOREAN', 180, 30, 4, 2, 25, 'MEDIUM', ['감자', '간장', '설탕', '참기름'], ['감자를 깍뚝 썹니다', '양념장에 조립니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['도시락']),
  createRecipe('r35', '두부조림', 'SIDE', 'KOREAN', 160, 10, 15, 8, 20, 'EASY', ['두부', '간장', '고춧가루', '파'], ['두부를 굽습니다', '양념장을 끼얹어 조립니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['건강', '도시락']),
  createRecipe('r36', '콩자반', 'SIDE', 'KOREAN', 100, 15, 8, 2, 40, 'MEDIUM', ['검은콩', '간장', '설탕'], ['콩을 불립니다', '양념장에 푹 삶습니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['건강']),
  createRecipe('r37', '우엉조림', 'SIDE', 'KOREAN', 90, 18, 2, 1, 30, 'MEDIUM', ['우엉', '간장', '물엿'], ['우엉을 채 썹니다', '간장 양념에 볶고 조립니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['건강']),
  createRecipe('r38', '도토리묵 무침', 'SIDE', 'KOREAN', 80, 15, 1, 2, 10, 'EASY', ['도토리묵', '상추', '김가루', '간장양념'], ['묵을 썹니다', '야채와 함께 버무립니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['다이어트']),
  createRecipe('r39', '호박전', 'SIDE', 'KOREAN', 150, 15, 3, 10, 20, 'EASY', ['애호박', '부침가루', '계란'], ['호박을 썹니다', '옷을 입혀 굽습니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600'),
  createRecipe('r40', '김치전', 'SIDE', 'KOREAN', 250, 30, 5, 12, 15, 'EASY', ['김치', '부침가루', '물'], ['김치를 썹니다', '반죽하여 굽습니다'], 'https://images.unsplash.com/photo-1620589125156-fd5028c5e05b?q=80&w=600', ['야식']),
];

export const DUMMY_INGREDIENTS: Ingredient[] = [
  { id: 'i1', name: '김치', category: 'PROCESSED', quantity: 1, unit: '포기', expiryDate: '2024-06-01', storage: 'FRIDGE', image: '🥬' },
  { id: 'i2', name: '계란', category: 'DAIRY', quantity: 10, unit: '개', expiryDate: '2024-04-30', storage: 'FRIDGE', image: '🥚' },
  { id: 'i3', name: '돼지고기', category: 'MEAT', quantity: 600, unit: 'g', expiryDate: '2024-04-20', storage: 'FREEZER', image: '🥓' },
  { id: 'i4', name: '양파', category: 'VEGETABLE', quantity: 3, unit: '개', expiryDate: '2024-05-15', storage: 'ROOM', image: '🧅' },
  { id: 'i5', name: '두부', category: 'PROCESSED', quantity: 1, unit: '모', expiryDate: '2024-04-25', storage: 'FRIDGE', image: '🧊' },
  { id: 'i6', name: '대파', category: 'VEGETABLE', quantity: 1, unit: '단', expiryDate: '2024-05-01', storage: 'FRIDGE', image: '🎋' },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: '무항생제 특란 30구',
    price: 8500,
    discountRate: 10,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1516482738497-146786c6eb8a?q=80&w=300&auto=format&fit=crop',
    tags: ['베스트', '세일'],
    link: '#',
    category: '신선식품'
  },
  {
    id: 'p2',
    name: '한돈 삼겹살 500g',
    price: 15000,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1602494359851-dd2671552430?q=80&w=300&auto=format&fit=crop',
    tags: ['핫딜'],
    link: '#',
    category: '정육'
  },
  {
    id: 'p3',
    name: '친환경 시금치 1단',
    price: 3500,
    rating: 4.2,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=300&auto=format&fit=crop',
    tags: [],
    link: '#',
    category: '신선식품'
  }
];

export const TODAY_MEAL: DailyMealPlan = {
  date: new Date().toISOString().split('T')[0],
  meals: {
    BREAKFAST: [
        { recipe: DUMMY_RECIPES[1], memberIds: ['m1', 'm2', 'm3'] }, // Rice
        { recipe: DUMMY_RECIPES[3], memberIds: ['m1', 'm2', 'm3'] }, // Soup
    ],
    LUNCH: [
      { recipe: DUMMY_RECIPES[0], memberIds: ['m1', 'm2', 'm3'] }, // Rice
      { recipe: DUMMY_RECIPES[8], memberIds: ['m1', 'm2', 'm3'] }, // Soup
      { recipe: DUMMY_RECIPES[2], memberIds: ['m1', 'm2', 'm3'] }, // Main
      { recipe: DUMMY_RECIPES[3], memberIds: ['m1', 'm2', 'm3'] }, // Side
    ],
    DINNER: [
        { recipe: DUMMY_RECIPES[14], memberIds: ['m1', 'm2', 'm3'] }, // Curry
        { recipe: DUMMY_RECIPES[4], memberIds: ['m1', 'm2', 'm3'] }, // Side
    ]
  }
};

export const DUMMY_POSTS: Post[] = [
  {
    id: 'post1',
    userId: 'u3',
    userName: '요리왕비룡',
    userAvatar: 'https://ui-avatars.com/api/?name=Dragon',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=600',
    content: '주말에는 역시 냉털 비빔밥이죠! 🥗 아이들도 잘 먹어서 너무 좋아요.',
    likes: 42,
    date: '2024-05-20'
  },
  {
    id: 'post2',
    userId: 'u4',
    userName: '살림9단',
    userAvatar: 'https://ui-avatars.com/api/?name=Salim',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=600',
    content: '오늘 저녁은 간단하게 샐러드로 해결~ 식단관리 3일차입니다 화이팅!',
    likes: 28,
    date: '2024-05-19'
  },
];
